# documentation: https://github.com/dgtlmoon/changedetection.io/
# slogan: Website change detection monitor and notifications.
# tags: web, alert, monitor
# logo: svgs/changedetection.png
# port: 5000

services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    volumes:
      - changedetection-data:/datastore
    environment:
      - SERVICE_FQDN_CHANGEDETECTION_5000
      - PUID=1000
      - PGID=1000
      - BASE_URL=$SERVICE_FQDN_CHANGEDETECTION
      - PLAYWRIGHT_DRIVER_URL=ws://playwright-chrome:3000/?stealth=1&--disable-web-security=true
      # Hides the `Referer` header so that monitored websites can't see the changedetection.io hostname.
      - HIDE_REFERER=true
    depends_on:
      playwright-chrome:
        condition: service_started
    healthcheck:
      test: ["CMD", "echo", "ok"]
      interval: 5s
      timeout: 20s
      retries: 10
  playwright-chrome:
    image: dgtlmoon/sockpuppetbrowser:latest
    # cap_add:
    #   - SYS_ADMIN
    # SYS_ADMIN might be too much, but it can be needed on your platform https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-on-gitlabci
    restart: unless-stopped
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1024
      - SCREEN_DEPTH=16
      - MAX_CONCURRENT_CHROME_PROCESSES=10
    healthcheck:
      test: ["CMD", "echo", "ok"]
      interval: 5s
      timeout: 20s
      retries: 10
